### ISSUE TITLE
Chrome logs 'Uncaught (in promise) TypeError' on load

### ISSUE THREAD

**Issue by baardsen** [paulmillr/es6-shim#403]
Chrome dev (49.0.2623.23) logs an error to console when loading es6-shim.
![chromeerror](https://cloud.githubusercontent.com/assets/3453179/12679519/edca02f2-c6a4-11e5-858f-3a99f3de7d37.png)

The error seems to come from the `promiseResolveBroken ` test:

    var promiseResolveBroken = (function (Promise) {
      var p = Promise.resolve(5);
      p.constructor = {};
      var p2 = Promise.resolve(p);
      return (p === p2); // This *should* be false!
    }(globals.Promise));

One possible fix is to add an empty reject handler to the `p2` promise: 

    if (p2.then)
      p2.then(function() {}, function() {});`

**Comment by ljharb** [comment]
Generally speaking, warnings like this aren't something that need "fixing" - Firefox logs a warning about mutating prototypes, for example, because one of es6-shim's runtime checks needs to try to mutate a prototype to check compliance.

However, in this case, something like the fix you've suggested will indeed work - thanks for the suggestion!

**Comment by zloirock** [comment]
Just for info: https://github.com/zloirock/core-js/issues/159 / https://code.google.com/p/chromium/issues/detail?id=575314
