### ISSUE TITLE
About update a new release

### ISSUE THREAD

**Issue by juranjun** [paulmillr/es6-shim#477]
About this issue, we hope have a new release version if possible, thks
https://github.com/paulmillr/es6-shim/issues/475

Could you update a new release please, we also need new release for es6-shim in our front-end code, This software is very useful for us, our commiter expects a newer release version of es6-shim (the update time of the last version is too long from now, 2 years ago), so we expect you to upgrade a new version if possible, thank u.

**Comment by ljharb** [comment]
v0.35.7 has been published. It only contains a single fix.

The time since last publish is irrelevant - software is not "out of date" or "insecure" because it was last published decades ago, let alone years ago. Any system you have that naively complains about not updating things that have published no updates is harming your security.

**Comment by juranjun** [comment]
Thanks very much, our committer thinks that no update for a long time, may be the software is inactive, but I don't think so.

**Comment by ljharb** [comment]
Your committee is worse than incorrect; their stance will lead to much less secure applications.
